apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
        - name: print-message
          image: busybox
          command: ['sh', '-c', 'echo "This is a pre-install hook!"']
      restartPolicy: Never
